"""Shape editor persistence (shape.yaml) + the section_curves composition
it feeds — shared by shape_editor_server.py (the shape editor itself,
which writes this file) and editor_server.py (the placement editor, which
reads it so panel placement previews against whatever shape was last
saved — "the placement editor reads that file for its shell", per the
milestone-3 spec). Neither server imports the other; both import this.

Same pattern as layout.py's layout.yaml: a canonical dump so
save(load(x)) is a fixed point, loud validation, lossless round-trip.
Publish (glTF export) stays a separate explicit step — saving shape.yaml
never touches the exported binary.
"""

import math
from dataclasses import dataclass, field, replace
from pathlib import Path

import numpy as np
import yaml

from bodice import _perimeter_np

_HEADER = ("# shape.yaml — dress shape editor state (milestone 3).\n"
          "# Auto-generated by the shape editor; hand-edit only if you know\n"
          "# the format. Lossless round-trip: save(load(x)) == x.\n")

_NECK_FIELDS = ("cf_height", "peak_height", "peak_theta", "side_height",
                "cb_height", "rise_bow", "decay_rate", "cf_corner")
_SKIRT_FIELDS = ("hem_circumference", "dome_n", "fillet_radius", "fillet_type")


class ShapeError(ValueError):
    """Raised on a malformed/invalid shape.yaml — fails loudly, like
    layout.py's LayoutError."""


@dataclass
class ShapeState:
    a_points: list             # [(v_mm, a_mm), ...], sorted ascending v
    b_points: list             # [(v_mm, b_mm), ...]
    neckline: dict = field(default_factory=dict)      # subset of _NECK_FIELDS
    skirt_fillet: dict = field(default_factory=dict)  # reference only — see
                                                        # shape_editor_server's
                                                        # module docstring:
                                                        # INERT once curves
                                                        # are active


class ShapeCurves:
    """The section_curves interface ShellModel expects: .v_lo/.v_hi,
    .a(z)/.b(z)/.perimeter(z). Both semi-axes genuinely authored (PCHIP
    through control points, shape-preserving, not forced monotone).
    perimeter is pure Ramanujan, a derived output, never adjusted."""

    def __init__(self, a_fit, b_fit, v_lo, v_hi):
        self._a = a_fit
        self._b = b_fit
        self.v_lo = float(v_lo)
        self.v_hi = float(v_hi)

    def _clip(self, z):
        return np.clip(np.asarray(z, dtype=float), self.v_lo, self.v_hi)

    def a(self, z):
        return self._a(self._clip(z))

    def b(self, z):
        return self._b(self._clip(z))

    def perimeter(self, z):
        z = self._clip(z)
        return _perimeter_np(np.asarray(self.a(z)), np.asarray(self.b(z)))


def fit_points(points, name="points"):
    """[(v, y), ...] -> (PchipInterpolator, sorted v list). Shared
    validation: no duplicate v, at least 2 points."""
    from scipy.interpolate import PchipInterpolator
    pts = sorted((float(v), float(y)) for v, y in points)
    if len(pts) < 2:
        raise ShapeError(f"{name} needs at least 2 control points, got {len(pts)}")
    vs = [v for v, _ in pts]
    if len(set(vs)) != len(vs):
        raise ShapeError(f"{name}: duplicate v value")
    return PchipInterpolator(vs, [y for _, y in pts]), vs


def build_params_from_shape(base_params, shape: ShapeState, z_bottom, z_top):
    """base_params -> a new ShellParams with a(v)/b(v) replaced by the
    shape's curves (section_curves mode) and the neckline heights
    overridden where the shape specifies them. skirt_fillet is NOT
    applied — it's stored for reference only (see module docstring on
    why it's inert once curves are active); dropping it here rather than
    silently pretending it did something."""
    a_fit, a_vs = fit_points(shape.a_points, "a_points")
    b_fit, b_vs = fit_points(shape.b_points, "b_points")
    for vs, name in ((a_vs, "a_points"), (b_vs, "b_points")):
        if abs(vs[0] - z_bottom) > 1e-6 or abs(vs[-1] - z_top) > 1e-6:
            raise ShapeError(
                f"{name} must span [{z_bottom:.1f}, {z_top:.1f}] exactly; "
                f"got [{vs[0]:.1f}, {vs[-1]:.1f}]")
    curves = ShapeCurves(a_fit, b_fit, z_bottom, z_top)
    bodice = base_params.bodice
    neck_updates = {k: v for k, v in shape.neckline.items() if k in _NECK_FIELDS}
    if neck_updates and bodice is not None:
        bodice = replace(bodice, **neck_updates)
    return replace(base_params, depth_curve=None, section_curves=curves, bodice=bodice)


def _yaml_float(x):
    """repr() round-trips binary64 exactly — same convention layout.py's
    _yaml_float uses for theta/s, applied here to v/a/b mm values."""
    return repr(float(x))


def dump_shape(shape: ShapeState) -> str:
    """Canonical text for shape.yaml. Same input -> byte-identical
    output, so save(load(x)) is a fixed point."""
    lines = [_HEADER, "version: 1", "a_points:"]
    for v, y in shape.a_points:
        lines.append(f"  - [{_yaml_float(v)}, {_yaml_float(y)}]")
    lines.append("b_points:")
    for v, y in shape.b_points:
        lines.append(f"  - [{_yaml_float(v)}, {_yaml_float(y)}]")
    lines.append("neckline:" if shape.neckline else "neckline: {}")
    for k in _NECK_FIELDS:
        if k in shape.neckline:
            v = shape.neckline[k]
            lines.append(f"  {k}: {'true' if v is True else 'false' if v is False else _yaml_float(v)}")
    lines.append("skirt_fillet:" if shape.skirt_fillet else "skirt_fillet: {}")
    for k in _SKIRT_FIELDS:
        if k in shape.skirt_fillet and shape.skirt_fillet[k] is not None:
            v = shape.skirt_fillet[k]
            lines.append(f"  {k}: {v if isinstance(v, str) else _yaml_float(v)}")
    return "\n".join(lines) + "\n"


def load_shape(path) -> ShapeState:
    """Parse shape.yaml -> ShapeState. Fails loudly, listing every
    problem it can, same discipline as layout.py's load_layout."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except FileNotFoundError:
        raise ShapeError(f"shape file not found: {path}") from None
    except yaml.YAMLError as exc:
        raise ShapeError(f"shape file is not valid YAML: {exc}") from None

    if not isinstance(data, dict):
        raise ShapeError(f"invalid shape file {path}: top level must be a mapping")
    errors = []
    if data.get("version") != 1:
        errors.append(f"version: expected 1, got {data.get('version')!r}")
    for key in ("a_points", "b_points"):
        pts = data.get(key)
        if not isinstance(pts, list) or not pts:
            errors.append(f"{key}: must be a non-empty list")
    if errors:
        raise ShapeError(f"invalid shape file {path}: " + "; ".join(errors))

    def _points(key):
        out = []
        for i, row in enumerate(data[key]):
            if (not isinstance(row, (list, tuple)) or len(row) != 2
                    or not all(isinstance(x, (int, float)) for x in row)):
                raise ShapeError(f"{key}[{i}]: expected [v, y] numbers, got {row!r}")
            out.append((float(row[0]), float(row[1])))
        return out

    neckline = data.get("neckline") or {}
    skirt_fillet = data.get("skirt_fillet") or {}
    if not isinstance(neckline, dict):
        raise ShapeError(f"neckline must be a mapping, got {neckline!r}")
    if not isinstance(skirt_fillet, dict):
        raise ShapeError(f"skirt_fillet must be a mapping, got {skirt_fillet!r}")
    return ShapeState(a_points=_points("a_points"), b_points=_points("b_points"),
                      neckline=dict(neckline), skirt_fillet=dict(skirt_fillet))


def save_shape(path, shape: ShapeState) -> str:
    text = dump_shape(shape)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return text
