"""Shape editor persistence (shape.yaml) + the section_curves composition
it feeds — shared by shape_editor_server.py (the shape editor itself,
which writes this file) and editor_server.py (the placement editor, which
reads it so panel placement previews against whatever shape was last
saved — "the placement editor reads that file for its shell", per the
milestone-3 spec). Neither server imports the other; both import this.

Same pattern as layout.py's layout.yaml: a canonical dump so
save(load(x)) is a fixed point, loud validation, lossless round-trip.
Publish (glTF export) stays a separate explicit step — saving shape.yaml
never touches the exported binary.

COMPOUND FRONT/BACK (review round 2): b(v) is no longer one shared
curve. Sections are the compound of two half-ellipses sharing a(v) --
front semi-axes (a, b_front), back semi-axes (a, b_back) -- exactly the
family compound.py's CompoundShellModel already implements (theta-aware
equal-arc parameterization, tangent-continuous at the side seam by
construction: cos(90 deg) = 0 kills the b-dependence exactly at the
join, so front and back always meet at (a, 0, z) regardless of how far
b_front and b_back diverge). What compound.py got wrong for THIS use
was CompoundDepth's plumbing, not the section geometry: CompoundDepth
SOLVES a(v) against a frozen circumference schedule -- the old
pipeline. CompoundShapeCurves below reuses CompoundShellModel entirely
unmodified (duck-typed via is_compound=True, see shell.py's dispatch)
but authors a(v) directly and derives perimeter as the mean of the two
Ramanujan formulas (compound.compound_perimeter) -- nothing is solved.

GENERATORS, NOT LIVE CONTROLS (review round 1): hem_circumference,
dome_n, fillet_radius/type, and the bust plateau span/depth used to
shape a(z)/b(z) directly; now that those are drawn, a live control that
no longer does anything is worse than no control. The bust construction
is bust="plateau" (PlateauBustDepth, wired into dress_params() as a
selectable option in round 3 -- the committed /dress shell's own
default is unchanged, still bust="apex") at the APPROVED settings:
theta pinned to the value that gives exactly 87.5mm true lateral width
at v=181 (half the measured 175mm breast tip distance), CF depth pinned
to 123.0mm (see shell.py's PLATEAU_THETA_DEG/PLATEAU_CF_DEPTH_MM).
generate_seed_curves()
below is the "seed curve from parameters" action -- it builds the
ordinary analytic committed-family shell (dress_params()) from those
parameters and samples it at the seed grid, producing a STARTING POINT
to drag from, not a persistent binding. The generator's raw parameters
are saved alongside the resulting curves for provenance (what this
shape started from) but are never reapplied on load -- the curves are
the source of truth once generated.
"""

import math
from dataclasses import dataclass, field, replace
from pathlib import Path

import numpy as np
import yaml

from bodice import _perimeter_np
from compound import compound_perimeter
from shell import ShellModel

DEFAULT_SHAPE_PATH = Path(__file__).resolve().parent / "shape.yaml"

_HEADER = ("# shape.yaml — dress shape editor state (milestone 3).\n"
          "# Auto-generated by the shape editor; hand-edit only if you know\n"
          "# the format. Lossless round-trip: save(load(x)) == x.\n")

_NECK_FIELDS = ("cf_height", "peak_height", "peak_theta", "side_height",
                "cb_height", "rise_bow", "decay_rate", "cf_corner")
_GENERATOR_FIELDS = ("hem_circumference", "dome_n", "fillet_radius",
                     "fillet_type", "plateau_theta_deg", "plateau_cf_depth_mm",
                     "plateau_radius_mm")

# Backdrop calibration — per-backdrop px<->mm registration from the shape
# editor's interactive calibration step (click the waist and hem
# landmarks, state their real heights). Storage-only, exactly like
# `generator`: it records how the backdrop images were registered when
# the curves were dragged, but is NEVER consumed by build_params_from_shape
# — the curves themselves are the source of truth, the calibration is
# provenance for whoever opens the shape next. "front" is the front-view
# backdrop (canvasA / a(v)); "trace" is the side-view backdrop (canvasB /
# b_front+b_back, a single profile trace shown mirrored on both sides).
_CALIB_BACKDROPS = ("front", "trace")
_CALIB_FIELDS = ("calibrated", "image", "image_natural_size", "waist_px", "hem_px",
                 "mm_per_px_v", "mm_per_px_h", "x_origin_px", "h_ref_method",
                 "h_ref", "implied_height_mm")


class ShapeError(ValueError):
    """Raised on a malformed/invalid shape.yaml — fails loudly, like
    layout.py's LayoutError."""


@dataclass
class ShapeState:
    a_points: list             # [(v_mm, a_mm), ...] — shared half-width
    b_front_points: list       # [(v_mm, b_mm), ...] — CF-side depth
    b_back_points: list        # [(v_mm, b_mm), ...] — CB-side depth
    neckline: dict = field(default_factory=dict)      # subset of _NECK_FIELDS
    generator: dict = field(default_factory=dict)     # provenance only — the
                                                        # parameters the curves
                                                        # were last GENERATED
                                                        # from (see module
                                                        # docstring); never
                                                        # reapplied on load
    backdrop_calibration: dict = field(default_factory=dict)  # provenance
                                                        # only — see
                                                        # _CALIB_BACKDROPS
                                                        # above; keyed
                                                        # "front"/"trace"


class CompoundShapeCurves:
    """Duck-types compound.CompoundDepth's interface for
    CompoundShellModel (.a/.da/.b_front/.db_front/.b_back/.db_back/.b/
    .perimeter/.P_front/.P_back/.dP_front/.dP_back/.v_lo/.v_hi) WITHOUT
    inheriting it: a is authored directly (PCHIP through dragged control
    points), not solved against a frozen schedule, so perimeter is a
    DERIVED output (compound_perimeter — the mean of the two Ramanujan
    formulas), never adjusted to hit a target. is_compound=True is the
    marker shell.py's ShellModel.__new__ dispatch checks to route to
    CompoundShellModel."""

    is_compound = True
    perimeter_residual_mm = 0.0   # nothing solved — exact by construction;
                                  # kept only so export_gltf's sidecar (which
                                  # reads this field on every depth_curve
                                  # variant) doesn't need a special case

    def __init__(self, a_fit, bf_fit, bb_fit, v_lo, v_hi):
        self._a, self._bf, self._bb = a_fit, bf_fit, bb_fit
        self._da, self._dbf, self._dbb = (a_fit.derivative(), bf_fit.derivative(),
                                          bb_fit.derivative())
        self.v_lo, self.v_hi = float(v_lo), float(v_hi)
        z = np.linspace(self.v_lo, self.v_hi, 2001)
        a, bf, bb = self.a(z), self.b_front(z), self.b_back(z)
        from scipy.interpolate import PchipInterpolator
        Pf = _perimeter_np(a, bf)
        Pb = _perimeter_np(a, bb)
        self._PF, self._PB = PchipInterpolator(z, Pf), PchipInterpolator(z, Pb)
        self._dPF, self._dPB = self._PF.derivative(), self._PB.derivative()

    def _clip(self, z):
        return np.clip(np.asarray(z, dtype=float), self.v_lo, self.v_hi)

    def a(self, z):
        return np.asarray(self._a(self._clip(z)), dtype=float)

    def da(self, z):
        return np.asarray(self._da(self._clip(z)), dtype=float)

    def b_front(self, z):
        return np.asarray(self._bf(self._clip(z)), dtype=float)

    def db_front(self, z):
        return np.asarray(self._dbf(self._clip(z)), dtype=float)

    def b_back(self, z):
        return np.asarray(self._bb(self._clip(z)), dtype=float)

    def db_back(self, z):
        return np.asarray(self._dbb(self._clip(z)), dtype=float)

    def b(self, z):
        """Front half-depth — documented alias, same convention as
        compound.CompoundDepth.b."""
        return self.b_front(z)

    def perimeter(self, z):
        z = self._clip(z)
        return compound_perimeter(self.a(z), self.b_front(z), self.b_back(z))

    def P_front(self, z):
        return np.asarray(self._PF(self._clip(z)), dtype=float)

    def P_back(self, z):
        return np.asarray(self._PB(self._clip(z)), dtype=float)

    def dP_front(self, z):
        return np.asarray(self._dPF(self._clip(z)), dtype=float)

    def dP_back(self, z):
        return np.asarray(self._dPB(self._clip(z)), dtype=float)

    def theta_junction_deg(self, z):
        """Equal-arc azimuth where the two half-ellipses meet. 90 exactly
        when b_front == b_back; shifts once they diverge."""
        pf, pb = self.P_front(z), self.P_back(z)
        return 180.0 * pf / (pf + pb)


def fit_points(points, name="points"):
    """[(v, y), ...] -> (PchipInterpolator, sorted v list). Shared
    validation: no duplicate v, at least 2 points."""
    from scipy.interpolate import PchipInterpolator
    pts = sorted((float(v), float(y)) for v, y in points)
    if len(pts) < 2:
        raise ShapeError(f"{name} needs at least 2 control points, got {len(pts)}")
    vs = [v for v, _ in pts]
    if len(set(vs)) != len(vs):
        raise ShapeError(f"{name}: duplicate v value")
    return PchipInterpolator(vs, [y for _, y in pts]), vs


def _check_domain(vs, name, z_bottom, z_top):
    if abs(vs[0] - z_bottom) > 1e-6 or abs(vs[-1] - z_top) > 1e-6:
        raise ShapeError(
            f"{name} must span [{z_bottom:.1f}, {z_top:.1f}] exactly; "
            f"got [{vs[0]:.1f}, {vs[-1]:.1f}]")


def build_params_from_shape(base_params, shape: ShapeState, z_bottom, z_top):
    """base_params -> a new ShellParams with compound section_curves
    replacing depth_curve entirely, and the neckline heights overridden
    where the shape specifies them."""
    a_fit, a_vs = fit_points(shape.a_points, "a_points")
    bf_fit, bf_vs = fit_points(shape.b_front_points, "b_front_points")
    bb_fit, bb_vs = fit_points(shape.b_back_points, "b_back_points")
    for vs, name in ((a_vs, "a_points"), (bf_vs, "b_front_points"),
                     (bb_vs, "b_back_points")):
        _check_domain(vs, name, z_bottom, z_top)
    curves = CompoundShapeCurves(a_fit, bf_fit, bb_fit, z_bottom, z_top)
    bodice = base_params.bodice
    neck_updates = {k: v for k, v in shape.neckline.items() if k in _NECK_FIELDS}
    if neck_updates and bodice is not None:
        bodice = replace(bodice, **neck_updates)
    return replace(base_params, depth_curve=curves, section_curves=None, bodice=bodice)


def apply_shape_if_present(params, shape_path=None):
    """THE single integration point between the shape editor and every
    shell-building entry point: if shape.yaml exists, its a(v)/b(v)
    curves become `params`'s semi-axes (section_curves mode, built via
    build_params_from_shape above). shape.yaml's neckline is deliberately
    NOT reapplied — the caller keeps its own authority over neckline/
    fillet knobs rather than the two tools fighting over the same
    control. A no-op when the file is absent, so every existing behavior
    (dress_params(), the plain committed shell) is unchanged.

    Called from BOTH editor_server.py (the live placement editor) AND
    export_gltf.py (the publish step) — so publish can never bake a shell
    independently of shape.yaml, regardless of which entry point (the
    editor's /api/publish, or running export_gltf.py directly as a
    script) triggers it. Before this was shared, only the editor's own
    HTTP handler picked shape.yaml up; a direct `python3 export_gltf.py`
    silently ignored it — that gap is what this closes."""
    path = Path(shape_path) if shape_path is not None else DEFAULT_SHAPE_PATH
    if not path.exists():
        return params
    saved = replace(load_shape(path), neckline={})
    probe = ShellModel(params)   # domain (z_bottom/z_top) only; cheap
    return build_params_from_shape(params, saved, probe.z_bottom, probe.z_top)


def _yaml_float(x):
    """repr() round-trips binary64 exactly — same convention layout.py's
    _yaml_float uses for theta/s, applied here to v/a/b mm values."""
    return repr(float(x))


def _dump_points(lines, key, points):
    lines.append(f"{key}:")
    for v, y in points:
        lines.append(f"  - [{_yaml_float(v)}, {_yaml_float(y)}]")


def _dump_px(lines, key, indent, px):
    pad = "  " * indent
    lines.append(f"{pad}{key}: [{_yaml_float(px[0])}, {_yaml_float(px[1])}]")


def _dump_calibration(lines, calibration):
    lines.append("backdrop_calibration:" if calibration else "backdrop_calibration: {}")
    for name in _CALIB_BACKDROPS:
        c = calibration.get(name)
        if not c:
            continue
        lines.append(f"  {name}:")
        for k in _CALIB_FIELDS:
            if k not in c or c[k] is None:
                continue
            v = c[k]
            if k in ("waist_px", "hem_px"):
                _dump_px(lines, k, 2, v)
            elif k == "h_ref":
                lines.append("    h_ref:")
                _dump_px(lines, "left_px", 3, v["left_px"])
                _dump_px(lines, "right_px", 3, v["right_px"])
                lines.append(f"      mm: {_yaml_float(v['mm'])}")
            elif k == "image_natural_size":
                lines.append(f"    image_natural_size: [{int(v[0])}, {int(v[1])}]")
            elif k == "calibrated":
                lines.append(f"    calibrated: {'true' if v else 'false'}")
            elif k in ("image", "h_ref_method"):
                lines.append(f"    {k}: {v}")
            else:
                lines.append(f"    {k}: {_yaml_float(v)}")


def dump_shape(shape: ShapeState) -> str:
    """Canonical text for shape.yaml. Same input -> byte-identical
    output, so save(load(x)) is a fixed point."""
    lines = [_HEADER, "version: 1"]
    _dump_points(lines, "a_points", shape.a_points)
    _dump_points(lines, "b_front_points", shape.b_front_points)
    _dump_points(lines, "b_back_points", shape.b_back_points)
    lines.append("neckline:" if shape.neckline else "neckline: {}")
    for k in _NECK_FIELDS:
        if k in shape.neckline:
            v = shape.neckline[k]
            lines.append(f"  {k}: {'true' if v is True else 'false' if v is False else _yaml_float(v)}")
    lines.append("generator:" if shape.generator else "generator: {}")
    for k in _GENERATOR_FIELDS:
        if k in shape.generator and shape.generator[k] is not None:
            v = shape.generator[k]
            lines.append(f"  {k}: {v if isinstance(v, str) else _yaml_float(v)}")
    _dump_calibration(lines, shape.backdrop_calibration)
    return "\n".join(lines) + "\n"


def load_shape(path) -> ShapeState:
    """Parse shape.yaml -> ShapeState. Fails loudly, listing every
    problem it can, same discipline as layout.py's load_layout."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except FileNotFoundError:
        raise ShapeError(f"shape file not found: {path}") from None
    except yaml.YAMLError as exc:
        raise ShapeError(f"shape file is not valid YAML: {exc}") from None

    if not isinstance(data, dict):
        raise ShapeError(f"invalid shape file {path}: top level must be a mapping")
    errors = []
    if data.get("version") != 1:
        errors.append(f"version: expected 1, got {data.get('version')!r}")
    for key in ("a_points", "b_front_points", "b_back_points"):
        pts = data.get(key)
        if not isinstance(pts, list) or not pts:
            errors.append(f"{key}: must be a non-empty list")
    if errors:
        raise ShapeError(f"invalid shape file {path}: " + "; ".join(errors))

    def _points(key):
        out = []
        for i, row in enumerate(data[key]):
            if (not isinstance(row, (list, tuple)) or len(row) != 2
                    or not all(isinstance(x, (int, float)) for x in row)):
                raise ShapeError(f"{key}[{i}]: expected [v, y] numbers, got {row!r}")
            out.append((float(row[0]), float(row[1])))
        return out

    neckline = data.get("neckline") or {}
    generator = data.get("generator") or {}
    if not isinstance(neckline, dict):
        raise ShapeError(f"neckline must be a mapping, got {neckline!r}")
    if not isinstance(generator, dict):
        raise ShapeError(f"generator must be a mapping, got {generator!r}")
    return ShapeState(a_points=_points("a_points"),
                      b_front_points=_points("b_front_points"),
                      b_back_points=_points("b_back_points"),
                      neckline=dict(neckline), generator=dict(generator),
                      backdrop_calibration=_load_calibration(data))


def _load_px(row, name):
    if (not isinstance(row, (list, tuple)) or len(row) != 2
            or not all(isinstance(x, (int, float)) for x in row)):
        raise ShapeError(f"{name}: expected [x, y] numbers, got {row!r}")
    return (float(row[0]), float(row[1]))


def _load_calibration(data):
    raw = data.get("backdrop_calibration") or {}
    if not isinstance(raw, dict):
        raise ShapeError(f"backdrop_calibration must be a mapping, got {raw!r}")
    out = {}
    for name in _CALIB_BACKDROPS:
        c = raw.get(name)
        if not c:
            continue
        if not isinstance(c, dict):
            raise ShapeError(f"backdrop_calibration.{name} must be a mapping, got {c!r}")
        entry = {}
        if "calibrated" in c:
            entry["calibrated"] = bool(c["calibrated"])
        if "image" in c:
            entry["image"] = str(c["image"])
        if c.get("image_natural_size") is not None:
            v = c["image_natural_size"]
            if not isinstance(v, (list, tuple)) or len(v) != 2:
                raise ShapeError(f"backdrop_calibration.{name}.image_natural_size: expected [w, h]")
            entry["image_natural_size"] = (int(v[0]), int(v[1]))
        for k in ("waist_px", "hem_px"):
            if c.get(k) is not None:
                entry[k] = _load_px(c[k], f"backdrop_calibration.{name}.{k}")
        for k in ("mm_per_px_v", "mm_per_px_h", "x_origin_px", "implied_height_mm"):
            if c.get(k) is not None:
                entry[k] = float(c[k])
        if "h_ref_method" in c:
            entry["h_ref_method"] = str(c["h_ref_method"])
        if c.get("h_ref"):
            href = c["h_ref"]
            if not isinstance(href, dict):
                raise ShapeError(f"backdrop_calibration.{name}.h_ref must be a mapping")
            entry["h_ref"] = {
                "left_px": _load_px(href.get("left_px"), f"backdrop_calibration.{name}.h_ref.left_px"),
                "right_px": _load_px(href.get("right_px"), f"backdrop_calibration.{name}.h_ref.right_px"),
                "mm": float(href["mm"]),
            }
        out[name] = entry
    return out


def save_shape(path, shape: ShapeState) -> str:
    text = dump_shape(shape)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return text
